title: Papercalc
email: realtechsolns@gmail.com
description: >-
  Papercalc is an open source project about technical calculations and 
  information about paper industry.

# Leave these EMPTY for now (if it was working before)
baseurl: ""
url: ""

twitter_username: jekyllrb
github_username: realtechsolutions

# Build settings
